### ISSUE TITLE
Reader panics after reading 1 record saying 'byte index 4 is out of bounds of `/`'

### ISSUE THREAD

**Issue by debugger22** [tmontaigu/dbase-rs#51]
Code:
```
use dbase;

fn main() {
    let mut reader = dbase::Reader::from_path("SAL.dbf").unwrap();
    for record_result in reader.iter_records() {
        if let Ok(record) = record_result {
            for (name, value) in record {
                match name.as_str() {
                    "BILLNO" => match value {
                        dbase::FieldValue::Character(Some(data)) => {
                            println!("{}", data);
                        }
                        _ => {}
                    },
                    _ => {}
                }
            }
        }
    }
}

```

Rust version: rustc 1.67.1 (d5a82bbd2 2023-02-07)
Stacktrace
```
thread 'main' panicked at 'byte index 4 is out of bounds of `/`', /home/debugger22/.cargo/registry/src/github.com-1ecc6299db9ec823/dbase-0.3.0/src/record/field.rs:487:20
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::str::slice_error_fail_rt
   3: core::str::slice_error_fail
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/str/mod.rs:86:9
   4: core::str::traits::<impl core::slice::index::SliceIndex<str> for core::ops::range::Range<usize>>::index
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/str/traits.rs:218:21
   5: core::str::traits::<impl core::ops::index::Index<I> for str>::index
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/str/traits.rs:65:9
   6: <dbase::record::field::Date as core::str::traits::FromStr>::from_str
             at /home/debugger22/.cargo/registry/src/github.com-1ecc6299db9ec823/dbase-0.3.0/src/record/field.rs:487:20
   7: core::str::<impl str>::parse
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/str/mod.rs:2351:9
   8: dbase::record::field::FieldValue::read_from
             at /home/debugger22/.cargo/registry/src/github.com-1ecc6299db9ec823/dbase-0.3.0/src/record/field.rs:312:43
   9: dbase::reading::FieldIterator<T>::read_field
             at /home/debugger22/.cargo/registry/src/github.com-1ecc6299db9ec823/dbase-0.3.0/src/reading.rs:548:15
  10: dbase::reading::FieldIterator<T>::read_next_field_impl
             at /home/debugger22/.cargo/registry/src/github.com-1ecc6299db9ec823/dbase-0.3.0/src/reading.rs:429:29
  11: dbase::reading::FieldIterator<T>::read_next_field
             at /home/debugger22/.cargo/registry/src/github.com-1ecc6299db9ec823/dbase-0.3.0/src/reading.rs:438:9
  12: <dbase::reading::FieldIterator<T> as core::iter::traits::iterator::Iterator>::next
             at /home/debugger22/.cargo/registry/src/github.com-1ecc6299db9ec823/dbase-0.3.0/src/reading.rs:567:15
  13: <&mut I as core::iter::traits::iterator::Iterator>::next
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/iter/traits/iterator.rs:3878:9
  14: <dbase::reading::Record as dbase::reading::ReadableRecord>::read_using
             at /home/debugger22/.cargo/registry/src/github.com-1ecc6299db9ec823/dbase-0.3.0/src/reading.rs:54:23
  15: <dbase::reading::RecordIterator<T,R> as core::iter::traits::iterator::Iterator>::next
             at /home/debugger22/.cargo/registry/src/github.com-1ecc6299db9ec823/dbase-0.3.0/src/reading.rs:611:26
  16: test_dbf::main
             at ./src/main.rs:5:26
  17: core::ops::function::FnOnce::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by tmontaigu** [comment]
Is the file that causes this publicly available ?

**Comment by segatheycallme** [comment]
Hi, I'm facing a similar issue where dbase is no longer able to read and parse a file after modifying a single record. The file can be read from other software and the record is indeed correctly modified. I was not able to find the cause of error but dbase writes normally in debug mode. 
In `src/file.rs` there is a debug assertion that causes unexpected behavior when not executed,
```rust
        // We don't need to update the file's inner position as we re-wrote the whole record
        debug_assert_eq!(
            self.file.file_position,
            self.file.inner.stream_position().unwrap()
        );
```
For some reason, not calling `self.file.inner.stream_position().unwrap()` results in unexpected behavior. Although this method takes a mutable reference, it shouldn't modify the stream in any way. A temporary fix may be changing this to assert on release builds or simply always calling the method.

I'm not sure where to go next in fixing this issue so any help would be appreciated. I can provide sanitized database files or code that reproduces this issue if needed.

**Comment by tmontaigu** [comment]
Yes the code + file to reproduce would be great

As long as I can reproduce 'm confident it will be easy to fix

**Comment by segatheycallme** [comment]
After some additional testing it appears that the header may be corrupted. Trying to change records using other tools produces errors and weird results. I believe that dbase parses the file fine but It's interesting that it doesn't report an error when writing to the file. Unfortunately, I was not given permission to share the file for further debugging. 
If I ever encounter a similar error with a public file I will raise another issue.

**Comment by tmontaigu** [comment]
Can you share the code ? It may still help
